services:
  mct-reid:
    image: kotoracompany/mct-reid:0.1.4
    container_name: mct_reid
    volumes:
      - ./env:/app/env
    networks:
      - mct-net
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh

  mct-cron-report:
    image: kotoracompany/mct-reid:0.1.4
    container_name: mct_cron_report
    volumes:
      - ./env:/app/env
    networks:
      - mct-net
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: ["python3", "auto_stats.py"]

  mct-cron-log:
    image: kotoracompany/mct-reid:0.1.4
    container_name: mct_cron_log
    volumes:
      - ./env:/app/env
    networks:
      - mct-net
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: ["python3", "auto_prune.py"]

networks:
  mct-net:
    name: mct-net
    external: true
