---
- name:Deploy Code to Jetson and Ubuntu Test Server
  hosts: all
  become: true
  environment:
    ANSIBLE_REMOTE_TEMP: ~/Workspaces/
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: "'ubuntu' in inventory_hostname"

    - name: Copy Camera and Tracking modules to Jetson
      synchronize:
        src: "{{ playbook_dir }}/camera/"
        dest: ~/Workspaces/
      delegate_to: "{{ inventory_hostname }}"
      when: "'jetson' in inventory_hostname"

    - name: Execute make build_base on Jetson
      command: "cd ~/Workspaces/camera && make build_base"
      delegate_to: "{{ inventory_hostname }}"
      when: "'jetson' in inventory_hostname"

    - name: Execute make build on Jetson
      command: "cd ~/Workspaces/camera && make build"
      delegate_to: "{{ inventory_hostname }}"
      when: "'jetson' in inventory_hostname"

    - name: Execute make start on Jetson
      command: "cd ~/Workspaces/camera && make start"
      delegate_to: "{{ inventory_hostname }}"
      when: "'jetson' in inventory_hostname"

    - name: Execute make build on Ubuntu Test Server
      command: "cd ~/Workspaces/reid && make build"
      delegate_to: "{{ inventory_hostname }}"
      when: "'ubuntu' in inventory_hostname"

    - name: Execute make start on Ubuntu Test Server
      command: "cd ~/Workspaces/reid && make start"
      delegate_to: "{{ inventory_hostname }}"
      when: "'ubuntu' in inventory_hostname"
 
