docker:
  compose_version: v2.4.1
  package: iph
remote_install_path: "/opt/{{ docker.package }}"


log:
  max_size: 2m
  max_file: 10
camera:
  compose_dir: "{{ remote_install_path }}/camera"
  image:
  service_name: "{{ docker.package }}-camera"

rtsp:
  Cam1: "rtsp://192.168.1.2:8554/stream"
  Cam2: "rtsp://192.168.1.2:8554/stream"
  Cam3: "rtsp://192.168.1.2:8554/stream"
  Cam4: "rtsp://192.168.1.2:8554/stream"
  Cam5: "rtsp://192.168.1.2:8554/stream"
  Cam6: "rtsp://192.168.1.2:8554/stream"
  Cam7: "rtsp://192.168.1.2:8554/stream"
  Cam8: "rtsp://192.168.1.2:8554/stream"
  Cam9: "rtsp://192.168.1.2:8554/stream"
  Cam10: "rtsp://192.168.1.2:8554/stream"
  Cam11: "rtsp://192.168.1.2:8554/stream"
  Cam12: "rtsp://192.168.1.2:8554/stream"
  Cam13: "rtsp://192.168.1.2:8554/stream"
  Cam14: "rtsp://192.168.1.2:8554/stream"
  Cam15: "rtsp://192.168.1.2:8554/stream"
  Cam16: "rtsp://192.168.1.2:8554/stream"
  Cam17: "rtsp://192.168.1.2:8554/stream"
  Cam18: "rtsp://192.168.1.2:8554/stream"
  Cam19: "rtsp://192.168.1.2:8554/stream"
  Cam20: "rtsp://192.168.1.2:8554/stream"
  Cam21: "rtsp://192.168.1.2:8554/stream"


  

tracking:
  compose_dir:
  image:
reid:
  compose_dir: "{{ remote_install_path }}/reid"
  image: ""
  

portal:
  compose_dir:
  image:
  
database:
  mongodb:
    compose_dir: "{{ remote_install_path }}/database"
    image: "mongo:6.0.1"
    service_name: "{{ docker.package }}-mongodb"
    username: admin
    password: password
    port: 27017
  mongoexp:
    compose_dir: "{{ remote_install_path }}/database"
    image: "mongo-express:1.0.0-alpha"
    service_name: "{{ docker.package }}-mongoexp"
    port: 8081

queue:
  compose_dir: "{{ remote_install_path }}/queue"
  redis:
    image: "redis:7.0.4"
    service_name: "{{ docker.package }}-redis"
    port: 6379









