version: "3"

networks:
  mct-net:
    name: mct-net
    external: true

services:
  mct-camera:
    image: kotoracompany/mct-camera:0.1.0
    container_name: mct_camera
    volumes: 
      - ./env/prod.json:/app/env/prod.json
    networks:
      - mct-net
    ports:
      - 9081:9081
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    
  mct-redis:
    image: redis:7.0.4
    container_name: mct_redis
    networks:
      - mct-net
    ports:
      - 6379:6379
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
