FROM python:3.8-slim

RUN apt-get update -y && \
    apt-get install -y telnet curl nano vim cmake && \
    apt-get install --reinstall build-essential -y

COPY ./requirements.txt /tmp/requirements.txt

RUN python3 -m pip install -U pip && \
    python3 -m pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

CMD ["bash"]